// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.MstAgentBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("region_id");

                    b.HasKey("Id");

                    b.ToTable("mst_agent_branches");
                });

            modelBuilder.Entity("backend.Models.MstAgentRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("mst_agent_regions");
                });

            modelBuilder.Entity("backend.Models.MstBlood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_blood");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "A",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "B",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "AB",
                            Status = "active"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "O",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("backend.Models.MstCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "บ. กรุงเทพประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "บ. กรุงเทพประกันสุขภาพ",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "บ. กรุงไทยพานิชประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "บ. กลางคุ้มครองผู้ประสบภัยจากรถ",
                            Status = "active"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "บ. ชับบ์สามัคคีประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "บ. โตเกียวมารีนประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "บ. ทิพยประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "บ. เทเวศประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "บ. ไทยไพบูลย์ประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "บ. ไทยวิวัฒน์ประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "บ. ไทยศรีประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "บ. ไทยเศรษฐกิจประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "บ. นวกิจประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "บ. บางกอกสหประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            Name = "บ. ประกันภัยไทยวิวัฒน์",
                            Status = "active"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            Name = "บ. เมืองไทยประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            Name = "บ. สินมั่นคงประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            Name = "บ. อาคเนย์ประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            Name = "บ. อินทรประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 20,
                            Name = "บ. เอเชียประกันภัย 1950",
                            Status = "active"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 21,
                            Name = "บ. แอลเอ็มจี ประกันภัย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 22,
                            Name = "บ. เอไอจี ประกันภัย (ประเทศไทย)",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("backend.Models.MstDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DistrictEng")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("district_english");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("DistrictThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("district_thai");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.HasKey("Id");

                    b.ToTable("mst_districts");
                });

            modelBuilder.Entity("backend.Models.MstExpertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_expertises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "ประกันรถยนต์",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "ประกันอัคคีภัย/ทรัพย์สิน",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "ประกันอุบัติเหตุ",
                            Status = "active"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "ประกันสุขภาพ",
                            Status = "active"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "ประกันเดินทาง/ทางทะเล",
                            Status = "active"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "ประกันการก่อสร้าง/วิศวกรรม",
                            Status = "active"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "ประกันภัยความรับผิดของกรรมการ/ผู้บริหาร",
                            Status = "active"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "ประกันภัยความรับผิด",
                            Status = "active"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "ประกันภัยด้านการเงิน/ค้ำประกัน",
                            Status = "active"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "ประกันภัยด้านสิทธิบัตร",
                            Status = "active"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "ประกันภัยทางทะเล/ขนส่ง",
                            Status = "active"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "ประกันอื่นๆ",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("backend.Models.MstGender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "ชาย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "หญิง",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("backend.Models.MstProvince", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProvinceEng")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_english");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<string>("ProvinceThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_thai");

                    b.HasKey("Id");

                    b.ToTable("mst_provinces");
                });

            modelBuilder.Entity("backend.Models.MstReligion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_religion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "พุทธ",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "คริสต์",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "อิสลาม",
                            Status = "active"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "ซิกข์",
                            Status = "active"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "ฮินดู",
                            Status = "active"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "อื่นๆ",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("backend.Models.MstRenewBasic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agent_type");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("course_name");

                    b.Property<int?>("DateId")
                        .HasColumnType("int")
                        .HasColumnName("date_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_renew_basic");
                });

            modelBuilder.Entity("backend.Models.MstRenewCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_renew_course");
                });

            modelBuilder.Entity("backend.Models.MstRenewDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CourseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("course_date");

                    b.Property<string>("CourseDateDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("course_date_display");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_renew_dates");
                });

            modelBuilder.Entity("backend.Models.MstRenewOther", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DateId")
                        .HasColumnType("int")
                        .HasColumnName("date_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<int>("PillarId")
                        .HasColumnType("int")
                        .HasColumnName("pillar_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.ToTable("mst_renew_other");
                });

            modelBuilder.Entity("backend.Models.MstRenewPillar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_renew_pillars");
                });

            modelBuilder.Entity("backend.Models.MstSubDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("SubDistrictEng")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sub_district_english");

                    b.Property<int>("SubDistrictId")
                        .HasColumnType("int")
                        .HasColumnName("sub_district_id");

                    b.Property<string>("SubDistrictThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sub_district_thai");

                    b.Property<string>("Zipcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("postal_code");

                    b.HasKey("Id");

                    b.ToTable("mst_sub_districts");
                });

            modelBuilder.Entity("backend.Models.MstTerritory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_territories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "ภาคกลาง",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "ภาคเหนือ",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "ภาคตะวันออกเฉียงเหนือ",
                            Status = "active"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "ภาคตะวันออก",
                            Status = "active"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "ภาคตะวันตก",
                            Status = "active"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "ภาคใต้",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("backend.Models.MstTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("mst_titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "นาย",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "นาง",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "นางสาว",
                            Status = "active"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "ด.ช.",
                            Status = "active"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "ด.ญ.",
                            Status = "active"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "ยศ/อื่นๆ (โปรดระบุ)",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("backend.Models.Person", b =>
                {
                    b.Property<string>("NationId")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("NationId");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BloodGroupId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstNameOldTh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstNameTh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodAllergy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IdCardExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastNameOldTh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastNameTh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleNameOldTh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleNameTh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("int");

                    b.Property<string>("TitleOldTh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleTh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationId");

                    b.ToTable("person");
                });

            modelBuilder.Entity("backend.Models.PersonAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressTypeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Road")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubDistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Village")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("personaddress");
                });

            modelBuilder.Entity("backend.Models.PersonAffiliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("BrokerBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrokerCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrokerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("ViriyahAgentCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("personaffiliation");
                });

            modelBuilder.Entity("backend.Models.PersonCourse", b =>
                {
                    b.Property<int>("PersonCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonCourseId"));

                    b.Property<int?>("CourseDateId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("RenewOtherId")
                        .HasColumnType("int");

                    b.HasKey("PersonCourseId");

                    b.HasIndex("NationId");

                    b.ToTable("personcourse");
                });

            modelBuilder.Entity("backend.Models.PersonLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LicenseIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("personlicense");
                });

            modelBuilder.Entity("backend.Models.PersonOther", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BrokerBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraTrainingInterest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InsuranceExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("OtherBusiness")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("NationId");

                    b.ToTable("personother");
                });

            modelBuilder.Entity("backend.Models.PersonOtherCompanies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("OtherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.HasIndex("OtherId");

                    b.ToTable("personothercompanies");
                });

            modelBuilder.Entity("backend.Models.PersonOtherSalesArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("OtherId")
                        .HasColumnType("int");

                    b.Property<int?>("TerritoriesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.HasIndex("OtherId");

                    b.ToTable("personothersalesarea");
                });

            modelBuilder.Entity("backend.Models.PersonOtherSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExpertiseId")
                        .HasColumnType("int");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("OtherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.HasIndex("OtherId");

                    b.ToTable("personotherspecialty");
                });

            modelBuilder.Entity("backend.Models.PersonRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool?>("PdpaConsent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("completion_time")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("confirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("start_time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("personregistration");
                });

            modelBuilder.Entity("backend.Models.PersonTraining5y", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("persontraining5y");
                });

            modelBuilder.Entity("backend.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalCourseRequirement")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("additional_course_requirement");

                    b.Property<string>("AddrDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("addr_district");

                    b.Property<string>("AddrHouseNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("addr_house_no");

                    b.Property<string>("AddrMoo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("addr_moo");

                    b.Property<string>("AddrPostcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("addr_postcode");

                    b.Property<string>("AddrProvince")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("addr_province");

                    b.Property<string>("AddrRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("addr_road");

                    b.Property<string>("AddrSoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("addr_soi");

                    b.Property<string>("AddrSubdistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("addr_subdistrict");

                    b.Property<string>("AddrVillage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("addr_village");

                    b.Property<string>("AgentBranch")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agent_branch");

                    b.Property<string>("AgentLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agent_level");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birth_date");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("blood_group");

                    b.Property<string>("BrokerBranch")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("broker_branch");

                    b.Property<string>("BrokerCompany")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("broker_company");

                    b.Property<string>("BrokerLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("broker_level");

                    b.Property<string>("CertifyTrue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("certify_true");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("completion_time");

                    b.Property<string>("Confirmed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("confirmed");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_address");

                    b.Property<string>("ContactDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_district");

                    b.Property<string>("ContactHouseNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_house_no");

                    b.Property<string>("ContactMoo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_moo");

                    b.Property<string>("ContactPostcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_postcode");

                    b.Property<string>("ContactProvince")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_province");

                    b.Property<string>("ContactRoad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_road");

                    b.Property<string>("ContactSoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_soi");

                    b.Property<string>("ContactSubdistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_subdistrict");

                    b.Property<string>("ContactVillage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_village");

                    b.Property<string>("CourseType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("course_type");

                    b.Property<string>("CourseTypeCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("course_type_code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DeductionPrivilege")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deduction_privilege");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("EmailAlt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email_alt");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("Expectation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expectation");

                    b.Property<string>("ExtraTrainingInterest")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extra_training_interest");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("facebook");

                    b.Property<string>("FirstNameEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name_en");

                    b.Property<string>("FirstNameEnPrev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name_en_prev");

                    b.Property<string>("FirstNameOldTh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name_old_th");

                    b.Property<string>("FirstNameTh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name_th");

                    b.Property<string>("FoodAllergy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("food_allergy");

                    b.Property<string>("FormName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("form_name");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gender");

                    b.Property<string>("HasChangedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("has_changed_name");

                    b.Property<string>("HasExperience")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("has_experience");

                    b.Property<string>("HighestEducation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("highest_education");

                    b.Property<DateTime?>("IdCardExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("id_card_expiry");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instagram");

                    b.Property<decimal?>("InsuranceExperienceYears")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("insurance_experience_years");

                    b.Property<string>("InsuranceSpecialty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("insurance_specialty");

                    b.Property<string>("LastModifiedTime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_modified_time");

                    b.Property<string>("LastNameEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name_en");

                    b.Property<string>("LastNameEnPrev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name_en_prev");

                    b.Property<string>("LastNameOldTh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name_old_th");

                    b.Property<string>("LastNameTh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name_th");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("license_expiry_date");

                    b.Property<DateTime?>("LicenseIssueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("license_issue_date");

                    b.Property<string>("LicenseNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("license_no");

                    b.Property<string>("LicenseStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("license_status");

                    b.Property<string>("LicenseType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("license_type");

                    b.Property<string>("LineId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("line_id");

                    b.Property<string>("MainBusiness")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("main_business");

                    b.Property<string>("MedicalCondition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("medical_condition");

                    b.Property<string>("MiddleNameEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("middle_name_en");

                    b.Property<string>("MiddleNameEnPrev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("middle_name_en_prev");

                    b.Property<string>("MiddleNameOldTh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("middle_name_old_th");

                    b.Property<string>("MiddleNameTh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("middle_name_th");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("national_id");

                    b.Property<string>("OtherInsuranceCompanies")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("other_insurance_companies");

                    b.Property<string>("PastTraining5y")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("past_training_5y");

                    b.Property<long?>("PastTraining5yCourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("past_training_5y_course_id");

                    b.Property<string>("PdpaConsent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pdpa_consent");

                    b.Property<string>("PhoneOtp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_otp");

                    b.Property<string>("PreviousCourses")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("previous_courses");

                    b.Property<string>("RegionAffiliation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region_affiliation");

                    b.Property<string>("RegionBangkok")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region_bangkok");

                    b.Property<string>("RegionCentralWest")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region_central_west");

                    b.Property<string>("RegionEast")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region_east");

                    b.Property<string>("RegionNorth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region_north");

                    b.Property<string>("RegionNortheast")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region_northeast");

                    b.Property<string>("RegionSouth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region_south");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("religion");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remark");

                    b.Property<string>("RenewAgent1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("renew_agent_1");

                    b.Property<string>("RenewAgent2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("renew_agent_2");

                    b.Property<string>("RenewAgent3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("renew_agent_3");

                    b.Property<string>("RenewBroker1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("renew_broker_1");

                    b.Property<string>("RenewBroker2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("renew_broker_2");

                    b.Property<string>("RenewBroker3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("renew_broker_3");

                    b.Property<string>("RenewOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("renew_other");

                    b.Property<long?>("RenewOtherCourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("renew_other_course_id");

                    b.Property<string>("SalesArea")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sales_area");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<string>("TitleCustom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title_custom");

                    b.Property<string>("TitleCustomPrev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title_custom_prev");

                    b.Property<string>("TitlePrev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title_prev");

                    b.Property<string>("TitleTh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title_th");

                    b.Property<string>("TrainingDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("training_date");

                    b.Property<string>("TrainingExemption")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("training_exemption");

                    b.Property<string>("TrainingExemptionYet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("training_exemption_yet");

                    b.Property<string>("TrainingFormat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("training_format");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("ViriyahAgentCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("viriyah_agent_code");

                    b.HasKey("Id");

                    b.ToTable("register");
                });

            modelBuilder.Entity("backend.Models.RegisterHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("EditedByType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("edited_by_type");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_data");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_data");

                    b.Property<int>("RegisterId")
                        .HasColumnType("int")
                        .HasColumnName("register_id");

                    b.HasKey("Id");

                    b.ToTable("register_history");
                });

            modelBuilder.Entity("backend.Models.RegistrationHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditedByType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegisterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.HasIndex("RegisterId");

                    b.ToTable("registrationhistory");
                });

            modelBuilder.Entity("backend.Models.SysConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("key_name");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("group_name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("sys_config");

                    b.HasData(
                        new
                        {
                            Key = "APP_ENV",
                            Description = "Environment (dev, uat, prd)",
                            Group = "system",
                            Value = "prd"
                        },
                        new
                        {
                            Key = "SESSION_TIMEOUT",
                            Description = "Session timeout in seconds",
                            Group = "system",
                            Value = "3600"
                        },
                        new
                        {
                            Key = "SYSTEM_IS_ONLINE",
                            Description = "Is system online",
                            Group = "system",
                            Value = "true"
                        },
                        new
                        {
                            Key = "SYSTEM_OPEN_PERIODS",
                            Description = "JSON array of open periods",
                            Group = "system",
                            Value = "[]"
                        },
                        new
                        {
                            Key = "tab4_label_branch",
                            Description = "Label for Branch",
                            Group = "tab4",
                            Value = "สาขา *"
                        },
                        new
                        {
                            Key = "tab4_hint_branch",
                            Description = "Hint for Branch",
                            Group = "tab4",
                            Value = "พิมพ์เพื่อค้นหาสาขา"
                        },
                        new
                        {
                            Key = "tab4_label_region",
                            Description = "Label for Region",
                            Group = "tab4",
                            Value = "ภาค *"
                        },
                        new
                        {
                            Key = "tab4_hint_region",
                            Description = "Hint for Region",
                            Group = "tab4",
                            Value = "ระบบจะเติมให้อัตโนมัติ"
                        },
                        new
                        {
                            Key = "tab4_label_agentcode",
                            Description = "Label for Agent Code",
                            Group = "tab4",
                            Value = "รหัสที่มีสัญญากับ บมจ.วิริยะประกันภัย *"
                        },
                        new
                        {
                            Key = "tab4_hint_agentcode",
                            Description = "Hint for Agent Code",
                            Group = "tab4",
                            Value = "ถ้าไม่ทราบ สอบถามสาขา หรือตัวแทน/นายหน้าที่ท่านสังกัด, ถ้าเป็นขอรับใบอนุญาต และยังไม่มีรหัส ให้กรอก 00000"
                        },
                        new
                        {
                            Key = "tab4_default_branch",
                            Description = "Default value for Branch",
                            Group = "tab4",
                            Value = ""
                        },
                        new
                        {
                            Key = "tab4_default_agentcode",
                            Description = "Default value for Agent Code",
                            Group = "tab4",
                            Value = ""
                        },
                        new
                        {
                            Key = "tab4_allowed_agent_types",
                            Description = "Allowed agent types (both, agent, broker)",
                            Group = "tab4",
                            Value = "both"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("admin_users");
                });

            modelBuilder.Entity("backend.Models.PersonAddress", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("backend.Models.PersonAffiliation", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany("Affiliations")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("backend.Models.PersonCourse", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany("Courses")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("backend.Models.PersonLicense", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany("Licenses")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("backend.Models.PersonOther", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany("Others")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("backend.Models.PersonOtherCompanies", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PersonOther", "PersonOther")
                        .WithMany("OtherCompanies")
                        .HasForeignKey("OtherId");

                    b.Navigation("Person");

                    b.Navigation("PersonOther");
                });

            modelBuilder.Entity("backend.Models.PersonOtherSalesArea", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PersonOther", "PersonOther")
                        .WithMany("SalesAreas")
                        .HasForeignKey("OtherId");

                    b.Navigation("Person");

                    b.Navigation("PersonOther");
                });

            modelBuilder.Entity("backend.Models.PersonOtherSpecialty", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PersonOther", "PersonOther")
                        .WithMany("Specialties")
                        .HasForeignKey("OtherId");

                    b.Navigation("Person");

                    b.Navigation("PersonOther");
                });

            modelBuilder.Entity("backend.Models.PersonRegistration", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany("Registrations")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("backend.Models.PersonTraining5y", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany("Trainings")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("backend.Models.RegistrationHistoryModel", b =>
                {
                    b.HasOne("backend.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PersonRegistration", "PersonRegistration")
                        .WithMany()
                        .HasForeignKey("RegisterId");

                    b.Navigation("Person");

                    b.Navigation("PersonRegistration");
                });

            modelBuilder.Entity("backend.Models.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Affiliations");

                    b.Navigation("Courses");

                    b.Navigation("Licenses");

                    b.Navigation("Others");

                    b.Navigation("Registrations");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("backend.Models.PersonOther", b =>
                {
                    b.Navigation("OtherCompanies");

                    b.Navigation("SalesAreas");

                    b.Navigation("Specialties");
                });
#pragma warning restore 612, 618
        }
    }
}
