USE thaiairp_iptc;
GO

TRUNCATE TABLE oic_raw_api_store;
GO

INSERT INTO oic_raw_api_store (id_card_number, source_system, http_status_code, raw_payload, received_at, created_at, is_latest)
VALUES 
('7489236817860', 'OIC_MOCK', 200, N'{"cis_profile":{"cis_id":"7489236817860","title_th":"นาย.","first_name_th":"สมชาย","last_name_th":"รักประกัน","person_status":"ACTIVE","aml_risk_level":"LOW","pep_status":false,"birth_date":"1990-05-15","gender":"Male","religion":"Buddhism","blood_group":"O","highest_education":"Bachelor","phone":"0812345678","email":"somchai@test.com","line_id":"somchai.line","facebook":"Somchai FB","instagram":"@somchai.ig","food_allergy":"Seafood","medical_condition":"None","emergency_contact_name":"สมศรี รักประกัน","emergency_contact_phone":"0899999999"},"address":{"house_no":"123/45","moo":"9","village":"หมู่บ้านสุขสันต์","soi":"ซอย 5","road":"สุขุมวิท","province":"กรุงเทพมหานคร","district":"วัฒนา","subdistrict":"คลองเตยเหนือ","postcode":"10110"},"training":{"course_type":"หลักสูตรผู้บริหาร","training_date":"2","selected_subjects":["วิชาประกันชีวิต","วิชาประกันวินาศภัย"],"previous_courses":["หลักสูตรขอรับใบอนุญาต","หลักสูตรต่ออายุครั้งที่ 1"]},"experience":{"insurance_experience_years":"5","occupation":"พนักงานบริษัท","broker_branch":"สาขาหลัก","extra_training_interest":"การบริหารความเสี่ยง","sales_territories":["1","2"],"other_insurance_companies":["3"]},"licenses":[{"license_number":"6601001200","issue_date":"2019-10-10","expire_date":"2024-10-09","type":"BROKER_LIFE","broker_type":"INDIVIDUAL","status":"ACTIVE"}],"affiliation":{"branch_id":"2","contract_code":"99999","broker_company":"บริษัท โบรคเกอร์ดี จำกัด"},"specialties":["ประกันต่อ","ประกันภัยรถยนต์"]}', GETDATE(), GETDATE(), 1),
('1613244338383', 'OIC_MOCK', 200, N'{"cis_profile":{"cis_id":"1613244338383","title_th":"น.ส.","first_name_th":"สมหญิง","last_name_th":"บริการดี","person_status":"ACTIVE","aml_risk_level":"LOW","pep_status":false,"birth_date":"1985-10-20","gender":"Female","religion":"Christianity","blood_group":"A","highest_education":"Master","phone":"0823334444","email":"somying@test.com","line_id":"","facebook":"","instagram":"","food_allergy":"","medical_condition":"","emergency_contact_name":"","emergency_contact_phone":""},"address":{"house_no":"99","moo":"","village":"","soi":"","road":"สีลม","province":"กรุงเทพมหานคร","district":"บางรัก","subdistrict":"สีลม","postcode":"10500"},"training":{"course_type":"ต่ออายุใบอนุญาต","training_date":"1","selected_subjects":[],"previous_courses":[]},"experience":{"insurance_experience_years":"10","occupation":"ตัวแทนอิสระ","broker_branch":"","extra_training_interest":"","sales_territories":["3"],"other_insurance_companies":[]},"licenses":[{"license_number":"6503011100","issue_date":"2022-03-01","expire_date":"2027-02-28","type":"AGENT_LIFE","broker_type":"","status":"ACTIVE"}],"affiliation":{"branch_id":"","contract_code":"","broker_company":""},"specialties":["สุขภาพ"]}', GETDATE(), GETDATE(), 1),
('9448106116565', 'OIC_MOCK', 200, N'{"cis_profile":{"cis_id":"9448106116565","title_th":"นาย.","first_name_th":"วิชัย","middle_name_th":"มงคล","last_name_th":"เสี่ยงสูง","person_status":"ACTIVE","aml_risk_level":"HIGH","pep_status":true,"id_card_expiry":"2030-02-28","birth_date":"1975-02-28","gender":"Male","religion":"Islam","blood_group":"B","highest_education":"High School","phone":"0891234567","email":"wichai@test.com","line_id":"wichai123","facebook":"Wichai Risk","instagram":"","food_allergy":"Peanuts","medical_condition":"Diabetes","emergency_contact_name":"มาลี เสี่ยงสูง","emergency_contact_phone":"0811112222"},"address":{"house_no":"11/1","moo":"2","village":"ตะวันทอแสง","soi":"1","road":"รามคำแหง","province":"กรุงเทพมหานคร","district":"บางกะปิ","subdistrict":"หัวหมาก","postcode":"10240"},"training":{"course_type":"ขอรับใบอนุญาตเป็นนายหน้าประกันวินาศภัย","training_date":"1","selected_subjects":["วิชาจรรยาบรรณนายหน้า"],"previous_courses":["หลักสูตรนายหน้า 1"]},"experience":{"insurance_experience_years":"2","occupation":"นักธุรกิจ","broker_branch":"สาขาบางกะปิ","extra_training_interest":"ประกันความรับผิด","sales_territories":["1"],"other_insurance_companies":["4"]},"licenses":[{"license_number":"6401055599","issue_date":"2020-05-15","expire_date":"2030-05-14","type":"BROKER_NON_LIFE","broker_type":"INDIVIDUAL","status":"ACTIVE"}],"affiliation":{"branch_id":"1","contract_code":"12345","broker_company":"บริษัท นายหน้าดีเด่น จำกัด"},"specialties":["อัคคีภัย"]}', GETDATE(), GETDATE(), 1);
GO
