USE thaiairp_iptc;
GO

TRUNCATE TABLE oic_agent_profile_store;
GO

INSERT INTO oic_agent_profile_store (id_card_number, source_system, verification_status, http_status_code, profile_payload, last_verified_at, created_at, updated_at, is_latest)
VALUES 
('7489236817860', 'OIC_MOCK', 'VERIFIED', 200, N'{ "nationalId": "7489236817860", "titleTh": "1", "firstNameTh": "สมชาย", "lastNameTh": "รักประกัน", "personStatus": "ACTIVE", "amlRiskLevel": "LOW", "pepStatus": false, "birthDate": "1990-05-15", "gender": "Male", "religion": "Buddhism", "bloodGroup": "O", "highestEducation": "Bachelor", "phoneOtp": "0812345678", "email": "somchai@test.com", "lineId": "somchai.line", "facebook": "Somchai FB", "instagram": "@somchai.ig", "foodAllergy": "Seafood", "medicalCondition": "None", "emergencyContactName": "สมศรี รักประกัน", "emergencyContactPhone": "0899999999", "addrHouseNo": "123/45", "addrMoo": "9", "addrVillage": "หมู่บ้านสุขสันต์", "addrSoi": "ซอย 5", "addrRoad": "สุขุมวิท", "addrProvince": "กรุงเทพมหานคร", "addrDistrict": "วัฒนา", "addrSubdistrict": "คลองเตยเหนือ", "addrPostcode": "10110", "previousCourses": ["หลักสูตรขอรับใบอนุญาต","หลักสูตรต่ออายุครั้งที่ 1"], "licenseNo": "6601001200", "licenseIssue": "2019-10-10", "licenseExpire": "2024-10-09", "agentType": "broker", "brokerType": "individual", "agentBranch": "2", "viriyaContractCode": "99999", "brokerAffiliation": "บริษัท โบรคเกอร์ดี จำกัด", "courseType": "1", "trainingDate": "2", "selectedSubjects": ["1", "2"], "insuranceExperienceYears": "5", "occupation": "พนักงานบริษัท", "brokerBranch": "สาขาหลัก", "extraTrainingInterest": "การบริหารความเสี่ยง", "salesTerritories": ["1", "2"], "otherInsuranceCompanies": ["3"], "insuranceSpecialty": [ "1", "2" ] }', GETDATE(), GETDATE(), GETDATE(), 1),
('1613244338383', 'OIC_MOCK', 'VERIFIED', 200, N'{ "nationalId": "1613244338383", "titleTh": "3", "firstNameTh": "สมหญิง", "lastNameTh": "บริการดี", "personStatus": "ACTIVE", "amlRiskLevel": "LOW", "pepStatus": false, "birthDate": "1985-10-20", "gender": "Female", "religion": "Christianity", "bloodGroup": "A", "highestEducation": "Master", "phoneOtp": "0823334444", "email": "somying@test.com", "lineId": "", "facebook": "", "instagram": "", "foodAllergy": "", "medicalCondition": "", "emergencyContactName": "", "emergencyContactPhone": "", "addrHouseNo": "99", "addrMoo": "", "addrVillage": "", "addrSoi": "", "addrRoad": "สีลม", "addrProvince": "กรุงเทพมหานคร", "addrDistrict": "บางรัก", "addrSubdistrict": "สีลม", "addrPostcode": "10500", "previousCourses": [], "licenseNo": "6503011100", "licenseIssue": "2022-03-01", "licenseExpire": "2027-02-28", "agentType": "agent", "brokerType": "", "agentBranch": "", "viriyaContractCode": "", "brokerAffiliation": "", "courseType": "2", "trainingDate": "1", "selectedSubjects": [], "insuranceExperienceYears": "10", "occupation": "ตัวแทนอิสระ", "brokerBranch": "", "extraTrainingInterest": "", "salesTerritories": ["3"], "otherInsuranceCompanies": [], "insuranceSpecialty": [ "4" ] }', GETDATE(), GETDATE(), GETDATE(), 1),
('9448106116565', 'OIC_MOCK', 'VERIFIED', 200, N'{ "nationalId": "9448106116565", "titleTh": "1", "firstNameTh": "วิชัย", "middleNameTh": "มงคล", "lastNameTh": "เสี่ยงสูง", "personStatus": "ACTIVE", "amlRiskLevel": "HIGH", "pepStatus": true, "idCardExpiry": "2030-02-28", "birthDate": "1975-02-28", "gender": "Male", "religion": "Islam", "bloodGroup": "B", "highestEducation": "High School", "phoneOtp": "0891234567", "email": "wichai@test.com", "lineId": "wichai123", "facebook": "Wichai Risk", "instagram": "", "foodAllergy": "Peanuts", "medicalCondition": "Diabetes", "emergencyContactName": "มาลี เสี่ยงสูง", "emergencyContactPhone": "0811112222", "addrHouseNo": "11/1", "addrMoo": "2", "addrVillage": "ตะวันทอแสง", "addrSoi": "1", "addrRoad": "รามคำแหง", "addrProvince": "กรุงเทพมหานคร", "addrDistrict": "บางกะปิ", "addrSubdistrict": "หัวหมาก", "addrPostcode": "10240", "previousCourses": ["หลักสูตรนายหน้า 1"], "licenseNo": "6401055599", "licenseIssue": "2020-05-15", "licenseExpire": "2030-05-14", "agentType": "broker", "brokerType": "individual", "agentBranch": "1", "viriyaContractCode": "12345", "brokerAffiliation": "บริษัท นายหน้าดีเด่น จำกัด", "courseType": "5", "trainingDate": "1", "selectedSubjects": ["3"], "insuranceExperienceYears": "2", "occupation": "นักธุรกิจ", "brokerBranch": "สาขาบางกะปิ", "extraTrainingInterest": "ประกันความรับผิด", "salesTerritories": ["1"], "otherInsuranceCompanies": ["4"], "insuranceSpecialty": [ "2" ] }', GETDATE(), GETDATE(), GETDATE(), 1);
GO
